config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'shop_items#new'

  resources :shop_items, only: %i[index new]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/shop_items_controller.rb
# frozen_string_literal: true

class ShopItemsController < ApplicationController
  def index
    @shop_items = ShopItemSearch.call(
      location: params[:location],
      cat_type: params[:cat_type]
    )
  end

  def new; end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Catsdealer
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'

    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/

  %body
    = yield

app/views/shop_items/index.haml
- if @shop_items.present?
  %p
    Best price for your location
    \- #{@shop_items.min_by { |item| item.price.to_f }.price}
  %table.table.table-striped
    %thead
      %tr
        %th Type
        %th Price
        %th Location
        %th Image
    %tbody
      - @shop_items.each do |item|
        %tr
          %td
            = item.name
          %td
            = item.price
          %td
            = item.location
          %td
            = image_tag(item.image, width: '150px')
- else
  %p
    Sorry, no cats for your location

app/views/shop_items/new.haml
.container
  .row
    .col-md-6.text-center.mx-auto
      = form_tag shop_items_path, method: :get, class: 'form-horizontal center' do
        .form-group
          %label Select cat type:
          = select_tag :cat_type, options_for_select(Settings.cat_types), class: 'form-control'
        .form-group
          %label Select your location:
          = select_tag :location, options_for_select(Settings.locations), class: 'form-control'

        %div
          = submit_tag 'Send request', class: 'btn btn-primary'